kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storageclass-azure-disk
provisioner: disk.csi.azure.com
parameters:
  skuname: Standard_LRS
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
